---
title: "Project 1"
author: "Alice Sin (16528144)"
date: "March 8, 2018"
output: html_document
---
```{r}
library("tidyverse")
library("phyloseq")
load("mothur_phyloseq.Rdata")
load("qiime2_phyloseq.RData")
```
```{r}
set.seed(4832)
m.norm = rarefy_even_depth(mothur, sample.size=100000)
m.perc = transform_sample_counts(m.norm, function(x) 100 * x/sum(x))
```

Load mothur physeq object  
```{r}
m.norm
```

Load QIIME2 physeq object
```{r}
qiime2
```
```{r}
plot_bar(mothur, fill="Phylum")
  #geom_bar(aes(fill=Phylum), stat="identity")
```

```{r, fig.width=30, fig.height=10}
#mothur_percent = transform_sample_counts(mothur, function(x) 100 * x/sum(x))
plot_bar(m.norm, fill="Order")+
  geom_bar(aes(fill=Order), stat="identity")
```

```{r}
m.norm %>% 
  subset_taxa(Order=="Flavobacteriales") #%>% 
  #estimate_richness(measures = c("Observed"))

```

```{r}
m.norm %>% 
  subset_taxa(Phylum=="Planctomycetes") #%>% 
  #estimate_richness(measures = c("Observed"))

```


```{r}
qiime2_percent = transform_sample_counts(qiime2, function(x) 100 * x/sum(x))
plot_bar(qiime2_percent, fill="Phylum")+
  geom_bar(aes(fill=Phylum), stat="identity")
```